### ISSUE TITLE
Running on Unleashed FW Crashes

### ISSUE THREAD

**Issue by V0lk3n** [Matt-London/pwnagotchi-flipper#1]
Hi, first of all thanks for this project :)
I follow it since you created it, waiting for setup instruction.

Yeaterday, i tried on my own, downloaded the repo, put it inside `applications_user` compiled using `fbt fap_pwn_zero`

The fap seem to be compiled without issue, i move it into tools folder of my sdcard.

Plug my pwnagotchi, wait that it totally boot (be sure by connecting my phone to it through bluetooth).

Finally open the app, it close it directly. Cant run the app successfully.

Any guidance?

Thanks for all and best regards!

V0lk3n

**Comment by Matt-London** [comment]
Thanks for letting me know! Currently, the interface is still very much in development. The code you likely compiled was when the ValueMutex was handing back null pointers which caused the Flipper to crash when it dereferenced them. I just now added a section in the README.md to note the project's current state, as well as another note under the setup instructions to explain that the interface is incomplete.

Currently, I am working on creating the system to have the Pwnagotchi and Flipper communicate, after that I will need to write an extension for the Pwnagotchi so that it can tell the Flipper what to draw. Overall, the interface is in its early stages.

Let me know if you have any remaining questions, if not I will close this issue. Thanks for the support, looking forward to having a working prototype for you!

**Comment by Matt-London** [comment]
Thank you for opening the issue to communicate your concern. I look forward to being able to provide a working version for you! I will now close this issue
