### ISSUE TITLE
Faces Optimized For Flipper

### ISSUE THREAD

**Issue by RogueMaster** [Matt-London/pwnagotchi-flipper#5]
Please review files found in this commit to pull so you can use in your app. I changed the faces so they look correct for F0.

https://github.com/RogueMaster/flipperzero-firmware-wPlugins/commit/8c45f8e9a921f61cda78ecdb2e58a244041d3e05

If you don't know how to include them, note how I include the animations folder from the application.fam in the app and also include the {app_name}_icons.h file so the compiled image assets get included for use.

**Comment by Matt-London** [comment]
@RogueMaster Took your advice and switched over to icons drawing. I used the icons that you had in your clock app as well as they seemed to be higher quality than mine. Happy to see you've taken an interest in the project and have added it to your firmware! I am looking to eventually move this into Bluetooth communication instead of UART.

Let me know if the latest commits have addressed your issue to your content and I will go ahead and close this. Thanks for the advice!

**Comment by RogueMaster** [comment]
I used ezgif to monochrome invert the images all at once 😄
